
=====================================================================================================
=== ver1 ===

---
AWSTemplateFormatVersion: 2010-09-09
Resources:
# --- Create role ---

  cloudformationRole:
    Type: 'AWS::IAM::Role'
    Properties:
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/ReadOnlyAccess'
       
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
                - config.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: "/"
      # Policies:   # Raf This creates inline policy
      #   -
      #     PolicyName: "LambdaAssumeRole"
      #     PolicyDocument:
      #       Version: "2012-10-17"
      #       Statement:
      #         -
      #           Effect: "Allow"
      #           Action: "sts:*"
      #           Resource: "*"
# --- Create role ---
  AWSConfigRule:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName:
        Ref: ConfigRuleName
      Description: Checks whether your CloudFormation stacks' actual configuration
        differs, or has drifted, from its expected configuration.
      InputParameters:
        cloudformationRoleArn:
          Fn::If:
          - cloudformationRoleArn
          - Ref: cloudformationRoleArn
          - Ref: AWS::NoValue
      Scope:
        ComplianceResourceTypes:
        - AWS::CloudFormation::Stack
      Source:
        Owner: AWS
        SourceIdentifier: CLOUDFORMATION_STACK_DRIFT_DETECTION_CHECK
      MaximumExecutionFrequency:
        Ref: MaximumExecutionFrequency
Parameters:
  ConfigRuleName:
    Type: String
    Default: cloudformation-stack-drift-detection-check
    Description: The name that you assign to the AWS Config rule.
    MinLength: '1'
    ConstraintDescription: This parameter is required.
  MaximumExecutionFrequency:
    Type: String
    Default: TwentyFour_Hours
    Description: The frequency that you want AWS Config to run evaluations for the
      rule.
    MinLength: '1'
    ConstraintDescription: This parameter is required.
    AllowedValues:
    - One_Hour
    - Three_Hours
    - Six_Hours
    - Twelve_Hours
    - TwentyFour_Hours
  cloudformationRoleArn:
    Type: String
    Default: cloudformationRole
    Description: The AWS CloudFormation role ARN with IAM policy permissions to detect
      drift for AWS CloudFormation Stacks
    MinLength: '1'
    ConstraintDescription: This parameter is required.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Required
      Parameters:
      - cloudformationRoleArn
    - Label:
        default: Optional
      Parameters: []
Conditions:
  cloudformationRoleArn:
    Fn::Not:
    - Fn::Equals:
      - ''
      - Ref: cloudformationRoleArn
